name: getx_project
description: "A new Flutter project."

publish_to: 'none'

# Android Version
version: 1.0.0+1

# IOS Version
# version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Get x
  get: ^4.7.2
  get_storage: ^2.1.1

  # Widget
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  animations: ^2.0.11
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.1.0

  # Utils
  device_info_plus: ^11.4.0
  network_info_plus: ^6.1.4
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  sentry_flutter: ^8.14.2


  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_remote_config: ^5.4.3

  # Local Storage
  shared_preferences: ^2.5.3





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - .env.dev
    - .env.prod































