name: getx_project
description: "A new Flutter project."

publish_to: 'none'

# Android Version
version: 1.0.0+1

# IOS Version
# version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Get x
  get: ^4.6.6
  get_storage: ^2.1.1

  # Widget
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  animations: ^2.0.11
  loading_animation_widget: ^1.2.1
  flutter_svg: ^2.0.10+1

  # Utils
  device_info_plus: ^10.0.1
  network_info_plus: ^5.0.2
  alice: ^0.4.1
  flutter_dotenv: ^5.1.0
  dio: ^5.4.1
  google_fonts: ^6.2.1


  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_remote_config: ^4.3.18

  # Local Storage
  shared_preferences: ^2.2.2





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env.dev
    - .env.prod































